apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-finance
  namespace: DEPLOY_ENV
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-finance
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: banking-finance
    spec:
      containers:
        - name: banking-finance
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "DEPLOY_ENV"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: banking-finance
  namespace: DEPLOY_ENV
spec:
  type: LoadBalancer
  selector:
    app: banking-finance
  ports:
    - port: 80
      targetPort: 8080
